# Generated by Django 5.2.7 on 2025-10-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(default=None, upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
